name: Chceck Node Version Setpu

on: push

jobs:
  NodeVersions:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [7,8,9]
        include: 
          - os: ubuntu-latest
            node-version: 9
            ubuntu_9: true

        exclude: 
          - os: ubuntu-latest
            node-version: [7,8] # check if the exclude taking list as inputs
          - os: macos-latest
            node-version: [7,9]

    runs-on: ubuntu-latest
    env:
      ubuntu_9: ${{ matrix.ubuntu_9 }}
    steps:
      - name: Node version
        run: node -v
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check version post setup
        run: node -v