name: Chceck Node Version Setpu

on: push

jobs:
  NodeVersions:
    strategy:
      matrix:
        node-version: [7,8,9]
    runs-on: ubuntu-latest
    steps:
      - name: Node version
        run: node -v
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check version post setup
        run: node -v